# Generated by Django 3.2.6 on 2022-06-17 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Введите имя, макс 64 символа', max_length=64, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию, макс 64 символа', max_length=64, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Фамилия')),
                ('phone', models.CharField(help_text='Укажите телефон для связи', max_length=128, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Телефон для связи')),
                ('email', models.EmailField(help_text='Укажите электронную почту', max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Email address')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Укажите, активен ли аккаунт', verbose_name='Аккаунт активен')),
                ('image', models.ImageField(blank=True, help_text='Разместите Вашу фотографию', null=True, upload_to='photos/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
