# Generated by Django 3.2.6 on 2022-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name="person's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="person's last name")),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin')], max_length=5)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
